import type { Camp } from "@/types/content";

// Newest first.
export const camps: Camp[] = [
  {
    slug: "phuket-taekwondo-2025",
    name: "Phuket International Taekwondo Camp",
    sport: "Taekwondo",
    location: "Phuket, Thailand",
    dates: "1–14 June 2025",
    year: 2025,
    note: "Led by Yong-Taek Yoo, head coach of the Thailand National Para Taekwondo Team.",
    photo: { src: "/images/camps/taekwondo.jpg", alt: "Taekwondo athletes mid-kick" },
  },
  {
    slug: "phuket-swimming-2025",
    name: "Phuket International Swimming Camp",
    sport: "Swimming",
    location: "Phuket, Thailand",
    dates: "1–14 June 2025",
    year: 2025,
    note: "Coached by two-time Olympic coach Paul Hardman.",
    photo: { src: "/images/camps/swimming.jpg", alt: "Swimmer doing freestyle" },
  },
  {
    slug: "phuket-basketball-2025",
    name: "Phuket International Basketball Camp",
    sport: "Basketball",
    location: "Phuket, Thailand",
    dates: "1–14 June 2025",
    year: 2025,
    note: "Coached by FIBA-certified senior coach Mateja Gorunović.",
    photo: { src: "/images/camps/basketball.jpg", alt: "Young basketball players dribbling" },
  },
  {
    slug: "ebre-talent-football",
    name: "EBRE Talent with Athleta",
    sport: "Football",
    location: "Spain",
    dates: "Spanish football camp",
    year: 2025,
    note: "A Spanish football camp run in partnership with EBRE Talent.",
  },
  {
    slug: "chonburi-swimming-2024",
    name: "Advanced Swimming International Camp",
    sport: "Swimming",
    location: "Chonburi, Thailand",
    venue: "Pattana Sports Resort",
    dates: "26 May – 10 June 2024",
    year: 2024,
    note: "With Pathways School Gurgaon. “Diving into growth”: reflections from students and parents.",
    photo: { src: "/images/camps/chonburi-swimming.jpg", alt: "Swimmers on the starting blocks at Pattana Sports Resort" },
  },
  {
    slug: "limitless-2023",
    name: "Limitless International Sports Camp",
    sport: "Multi-sport",
    location: "Phuket, Thailand",
    venue: "Prince of Songkla University",
    dates: "27 June – 8 July 2023",
    year: 2023,
    note: "With Pathways School Gurgaon.",
  },
];
